
#sources will be embedded in a cube
/gate/world/daughters/name cubeOfSources
/gate/world/daughters/insert box
/gate/cubeOfSources/setMaterial Air
/gate/cubeOfSources/geometry/setXLength 100 mm
/gate/cubeOfSources/geometry/setYLength 100 mm
/gate/cubeOfSources/geometry/setZLength 100 mm
/gate/cubeOfSources/placement/setTranslation 0. 0. 0. mm
/gate/cubeOfSources/vis/setColor blue
/gate/cubeOfSources/vis/forceWireframe
#/gate/cubeOfSources/vis/forceSolid
/gate/cubeOfSources/vis/setVisible 1

/gate/source/addSource background
/gate/source/background/setType backtoback
/gate/source/background/gps/centre 0. 0. 0. mm
/gate/source/background/gps/particle gamma
/gate/source/background/gps/energytype Mono
/gate/source/background/gps/monoenergy 0.511 MeV
/gate/source/background/gps/type Volume
/gate/source/background/gps/shape Para
/gate/source/background/gps/halfx 50 mm
/gate/source/background/gps/halfy 50 mm
/gate/source/background/gps/halfz 50 mm
/gate/source/background/gps/angtype iso

/gate/source/addSource source0_0
/gate/source/source0_0/setType backtoback
/gate/source/source0_0/gps/centre 0. 0. 0. mm
/gate/source/source0_0/gps/particle gamma
/gate/source/source0_0/gps/energytype Mono
/gate/source/source0_0/gps/monoenergy 0.511 MeV
/gate/source/source0_0/gps/type Volume
/gate/source/source0_0/gps/shape Sphere
/gate/source/source0_0/gps/radius 0.15 mm
/gate/source/source0_0/gps/angtype iso

/gate/source/addSource source0_1
/gate/source/source0_1/setType backtoback
/gate/source/source0_1/gps/centre 0. 0. 5. mm
/gate/source/source0_1/gps/particle gamma
/gate/source/source0_1/gps/energytype Mono
/gate/source/source0_1/gps/monoenergy 0.511 MeV
/gate/source/source0_1/gps/type Volume
/gate/source/source0_1/gps/shape Sphere
/gate/source/source0_1/gps/radius 0.15 mm
/gate/source/source0_1/gps/angtype iso

/gate/source/addSource source0_2
/gate/source/source0_2/setType backtoback
/gate/source/source0_2/gps/centre 0. 0. 10. mm
/gate/source/source0_2/gps/particle gamma
/gate/source/source0_2/gps/energytype Mono
/gate/source/source0_2/gps/monoenergy 0.511 MeV
/gate/source/source0_2/gps/type Volume
/gate/source/source0_2/gps/shape Sphere
/gate/source/source0_2/gps/radius 0.15 mm
/gate/source/source0_2/gps/angtype iso

/gate/source/addSource source0_3
/gate/source/source0_3/setType backtoback
/gate/source/source0_3/gps/centre 0. 0. 15. mm
/gate/source/source0_3/gps/particle gamma
/gate/source/source0_3/gps/energytype Mono
/gate/source/source0_3/gps/monoenergy 0.511 MeV
/gate/source/source0_3/gps/type Volume
/gate/source/source0_3/gps/shape Sphere
/gate/source/source0_3/gps/radius 0.15 mm
/gate/source/source0_3/gps/angtype iso

/gate/source/addSource source0_4
/gate/source/source0_4/setType backtoback
/gate/source/source0_4/gps/centre 0. 0. 20. mm
/gate/source/source0_4/gps/particle gamma
/gate/source/source0_4/gps/energytype Mono
/gate/source/source0_4/gps/monoenergy 0.511 MeV
/gate/source/source0_4/gps/type Volume
/gate/source/source0_4/gps/shape Sphere
/gate/source/source0_4/gps/radius 0.15 mm
/gate/source/source0_4/gps/angtype iso

/gate/source/addSource source0_5
/gate/source/source0_5/setType backtoback
/gate/source/source0_5/gps/centre 0. 0. 25. mm
/gate/source/source0_5/gps/particle gamma
/gate/source/source0_5/gps/energytype Mono
/gate/source/source0_5/gps/monoenergy 0.511 MeV
/gate/source/source0_5/gps/type Volume
/gate/source/source0_5/gps/shape Sphere
/gate/source/source0_5/gps/radius 0.15 mm
/gate/source/source0_5/gps/angtype iso

/gate/source/addSource source0_6
/gate/source/source0_6/setType backtoback
/gate/source/source0_6/gps/centre 0. 0. 30. mm
/gate/source/source0_6/gps/particle gamma
/gate/source/source0_6/gps/energytype Mono
/gate/source/source0_6/gps/monoenergy 0.511 MeV
/gate/source/source0_6/gps/type Volume
/gate/source/source0_6/gps/shape Sphere
/gate/source/source0_6/gps/radius 0.15 mm
/gate/source/source0_6/gps/angtype iso

/gate/source/addSource source0_7
/gate/source/source0_7/setType backtoback
/gate/source/source0_7/gps/centre 0. 0. 35. mm
/gate/source/source0_7/gps/particle gamma
/gate/source/source0_7/gps/energytype Mono
/gate/source/source0_7/gps/monoenergy 0.511 MeV
/gate/source/source0_7/gps/type Volume
/gate/source/source0_7/gps/shape Sphere
/gate/source/source0_7/gps/radius 0.15 mm
/gate/source/source0_7/gps/angtype iso

/gate/source/addSource source0_8
/gate/source/source0_8/setType backtoback
/gate/source/source0_8/gps/centre 0. 0. -5. mm
/gate/source/source0_8/gps/particle gamma
/gate/source/source0_8/gps/energytype Mono
/gate/source/source0_8/gps/monoenergy 0.511 MeV
/gate/source/source0_8/gps/type Volume
/gate/source/source0_8/gps/shape Sphere
/gate/source/source0_8/gps/radius 1 mm
/gate/source/source0_8/gps/angtype iso

/gate/source/addSource source0_9
/gate/source/source0_9/setType backtoback
/gate/source/source0_9/gps/centre 0. 0. -10. mm
/gate/source/source0_9/gps/particle gamma
/gate/source/source0_9/gps/energytype Mono
/gate/source/source0_9/gps/monoenergy 0.511 MeV
/gate/source/source0_9/gps/type Volume
/gate/source/source0_9/gps/shape Sphere
/gate/source/source0_9/gps/radius 1 mm
/gate/source/source0_9/gps/angtype iso

/gate/source/addSource source0_10
/gate/source/source0_10/setType backtoback
/gate/source/source0_10/gps/centre 0. 0. -15. mm
/gate/source/source0_10/gps/particle gamma
/gate/source/source0_10/gps/energytype Mono
/gate/source/source0_10/gps/monoenergy 0.511 MeV
/gate/source/source0_10/gps/type Volume
/gate/source/source0_10/gps/shape Sphere
/gate/source/source0_10/gps/radius 1 mm
/gate/source/source0_10/gps/angtype iso

/gate/source/addSource source0_11
/gate/source/source0_11/setType backtoback
/gate/source/source0_11/gps/centre 0. 0. -20. mm
/gate/source/source0_11/gps/particle gamma
/gate/source/source0_11/gps/energytype Mono
/gate/source/source0_11/gps/monoenergy 0.511 MeV
/gate/source/source0_11/gps/type Volume
/gate/source/source0_11/gps/shape Sphere
/gate/source/source0_11/gps/radius 1 mm
/gate/source/source0_11/gps/angtype iso

/gate/source/addSource source0_12
/gate/source/source0_12/setType backtoback
/gate/source/source0_12/gps/centre 0. 0. -25. mm
/gate/source/source0_12/gps/particle gamma
/gate/source/source0_12/gps/energytype Mono
/gate/source/source0_12/gps/monoenergy 0.511 MeV
/gate/source/source0_12/gps/type Volume
/gate/source/source0_12/gps/shape Sphere
/gate/source/source0_12/gps/radius 1 mm
/gate/source/source0_12/gps/angtype iso

/gate/source/addSource source0_13
/gate/source/source0_13/setType backtoback
/gate/source/source0_13/gps/centre 0. 0. -30. mm
/gate/source/source0_13/gps/particle gamma
/gate/source/source0_13/gps/energytype Mono
/gate/source/source0_13/gps/monoenergy 0.511 MeV
/gate/source/source0_13/gps/type Volume
/gate/source/source0_13/gps/shape Sphere
/gate/source/source0_13/gps/radius 1 mm
/gate/source/source0_13/gps/angtype iso

/gate/source/addSource source0_14
/gate/source/source0_14/setType backtoback
/gate/source/source0_14/gps/centre 0. 0. -35. mm
/gate/source/source0_14/gps/particle gamma
/gate/source/source0_14/gps/energytype Mono
/gate/source/source0_14/gps/monoenergy 0.511 MeV
/gate/source/source0_14/gps/type Volume
/gate/source/source0_14/gps/shape Sphere
/gate/source/source0_14/gps/radius 1 mm
/gate/source/source0_14/gps/angtype iso





/gate/source/addSource source1_0
/gate/source/source1_0/setType backtoback
/gate/source/source1_0/gps/centre 52. 0. 0. mm
/gate/source/source1_0/gps/particle gamma
/gate/source/source1_0/gps/energytype Mono
/gate/source/source1_0/gps/monoenergy 0.511 MeV
/gate/source/source1_0/gps/type Volume
/gate/source/source1_0/gps/shape Sphere
/gate/source/source1_0/gps/radius 0.15 mm
/gate/source/source1_0/gps/angtype iso

/gate/source/addSource source1_1
/gate/source/source1_1/setType backtoback
/gate/source/source1_1/gps/centre 52. 0. 5. mm
/gate/source/source1_1/gps/particle gamma
/gate/source/source1_1/gps/energytype Mono
/gate/source/source1_1/gps/monoenergy 0.511 MeV
/gate/source/source1_1/gps/type Volume
/gate/source/source1_1/gps/shape Sphere
/gate/source/source1_1/gps/radius 0.15 mm
/gate/source/source1_1/gps/angtype iso

/gate/source/addSource source1_2
/gate/source/source1_2/setType backtoback
/gate/source/source1_2/gps/centre 52. 0. 10. mm
/gate/source/source1_2/gps/particle gamma
/gate/source/source1_2/gps/energytype Mono
/gate/source/source1_2/gps/monoenergy 0.511 MeV
/gate/source/source1_2/gps/type Volume
/gate/source/source1_2/gps/shape Sphere
/gate/source/source1_2/gps/radius 0.15 mm
/gate/source/source1_2/gps/angtype iso

/gate/source/addSource source1_3
/gate/source/source1_3/setType backtoback
/gate/source/source1_3/gps/centre 52. 0. 15. mm
/gate/source/source1_3/gps/particle gamma
/gate/source/source1_3/gps/energytype Mono
/gate/source/source1_3/gps/monoenergy 0.511 MeV
/gate/source/source1_3/gps/type Volume
/gate/source/source1_3/gps/shape Sphere
/gate/source/source1_3/gps/radius 0.15 mm
/gate/source/source1_3/gps/angtype iso

/gate/source/addSource source1_4
/gate/source/source1_4/setType backtoback
/gate/source/source1_4/gps/centre 52. 0. 20. mm
/gate/source/source1_4/gps/particle gamma
/gate/source/source1_4/gps/energytype Mono
/gate/source/source1_4/gps/monoenergy 0.511 MeV
/gate/source/source1_4/gps/type Volume
/gate/source/source1_4/gps/shape Sphere
/gate/source/source1_4/gps/radius 0.15 mm
/gate/source/source1_4/gps/angtype iso

/gate/source/addSource source1_5
/gate/source/source1_5/setType backtoback
/gate/source/source1_5/gps/centre 52. 0. 25. mm
/gate/source/source1_5/gps/particle gamma
/gate/source/source1_5/gps/energytype Mono
/gate/source/source1_5/gps/monoenergy 0.511 MeV
/gate/source/source1_5/gps/type Volume
/gate/source/source1_5/gps/shape Sphere
/gate/source/source1_5/gps/radius 0.15 mm
/gate/source/source1_5/gps/angtype iso

/gate/source/addSource source1_6
/gate/source/source1_6/setType backtoback
/gate/source/source1_6/gps/centre 52. 0. 30. mm
/gate/source/source1_6/gps/particle gamma
/gate/source/source1_6/gps/energytype Mono
/gate/source/source1_6/gps/monoenergy 0.511 MeV
/gate/source/source1_6/gps/type Volume
/gate/source/source1_6/gps/shape Sphere
/gate/source/source1_6/gps/radius 0.15 mm
/gate/source/source1_6/gps/angtype iso

/gate/source/addSource source1_7
/gate/source/source1_7/setType backtoback
/gate/source/source1_7/gps/centre 52. 0. 35. mm
/gate/source/source1_7/gps/particle gamma
/gate/source/source1_7/gps/energytype Mono
/gate/source/source1_7/gps/monoenergy 0.511 MeV
/gate/source/source1_7/gps/type Volume
/gate/source/source1_7/gps/shape Sphere
/gate/source/source1_7/gps/radius 0.15 mm
/gate/source/source1_7/gps/angtype iso

/gate/source/addSource source1_8
/gate/source/source1_8/setType backtoback
/gate/source/source1_8/gps/centre 52. 0. -5. mm
/gate/source/source1_8/gps/particle gamma
/gate/source/source1_8/gps/energytype Mono
/gate/source/source1_8/gps/monoenergy 0.511 MeV
/gate/source/source1_8/gps/type Volume
/gate/source/source1_8/gps/shape Sphere
/gate/source/source1_8/gps/radius 1 mm
/gate/source/source1_8/gps/angtype iso

/gate/source/addSource source1_9
/gate/source/source1_9/setType backtoback
/gate/source/source1_9/gps/centre 52. 0. -10. mm
/gate/source/source1_9/gps/particle gamma
/gate/source/source1_9/gps/energytype Mono
/gate/source/source1_9/gps/monoenergy 0.511 MeV
/gate/source/source1_9/gps/type Volume
/gate/source/source1_9/gps/shape Sphere
/gate/source/source1_9/gps/radius 1 mm
/gate/source/source1_9/gps/angtype iso

/gate/source/addSource source1_10
/gate/source/source1_10/setType backtoback
/gate/source/source1_10/gps/centre 52. 0. -15. mm
/gate/source/source1_10/gps/particle gamma
/gate/source/source1_10/gps/energytype Mono
/gate/source/source1_10/gps/monoenergy 0.511 MeV
/gate/source/source1_10/gps/type Volume
/gate/source/source1_10/gps/shape Sphere
/gate/source/source1_10/gps/radius 1 mm
/gate/source/source1_10/gps/angtype iso

/gate/source/addSource source1_11
/gate/source/source1_11/setType backtoback
/gate/source/source1_11/gps/centre 52. 0. -20. mm
/gate/source/source1_11/gps/particle gamma
/gate/source/source1_11/gps/energytype Mono
/gate/source/source1_11/gps/monoenergy 0.511 MeV
/gate/source/source1_11/gps/type Volume
/gate/source/source1_11/gps/shape Sphere
/gate/source/source1_11/gps/radius 1 mm
/gate/source/source1_11/gps/angtype iso

/gate/source/addSource source1_12
/gate/source/source1_12/setType backtoback
/gate/source/source1_12/gps/centre 52. 0. -25. mm
/gate/source/source1_12/gps/particle gamma
/gate/source/source1_12/gps/energytype Mono
/gate/source/source1_12/gps/monoenergy 0.511 MeV
/gate/source/source1_12/gps/type Volume
/gate/source/source1_12/gps/shape Sphere
/gate/source/source1_12/gps/radius 1 mm
/gate/source/source1_12/gps/angtype iso

/gate/source/addSource source1_13
/gate/source/source1_13/setType backtoback
/gate/source/source1_13/gps/centre 52. 0. -30. mm
/gate/source/source1_13/gps/particle gamma
/gate/source/source1_13/gps/energytype Mono
/gate/source/source1_13/gps/monoenergy 0.511 MeV
/gate/source/source1_13/gps/type Volume
/gate/source/source1_13/gps/shape Sphere
/gate/source/source1_13/gps/radius 1 mm
/gate/source/source1_13/gps/angtype iso

/gate/source/addSource source1_14
/gate/source/source1_14/setType backtoback
/gate/source/source1_14/gps/centre 52. 0. -35. mm
/gate/source/source1_14/gps/particle gamma
/gate/source/source1_14/gps/energytype Mono
/gate/source/source1_14/gps/monoenergy 0.511 MeV
/gate/source/source1_14/gps/type Volume
/gate/source/source1_14/gps/shape Sphere
/gate/source/source1_14/gps/radius 1 mm
/gate/source/source1_14/gps/angtype iso





/gate/source/background/attachTo cubeOfSources
/gate/source/source0_0/attachTo cubeOfSources
/gate/source/source0_1/attachTo cubeOfSources
/gate/source/source0_2/attachTo cubeOfSources
/gate/source/source0_3/attachTo cubeOfSources
/gate/source/source0_4/attachTo cubeOfSources
/gate/source/source0_5/attachTo cubeOfSources
/gate/source/source0_6/attachTo cubeOfSources
/gate/source/source0_7/attachTo cubeOfSources
/gate/source/source1_0/attachTo cubeOfSources
/gate/source/source1_1/attachTo cubeOfSources
/gate/source/source1_2/attachTo cubeOfSources
/gate/source/source1_3/attachTo cubeOfSources
/gate/source/source1_4/attachTo cubeOfSources
/gate/source/source1_5/attachTo cubeOfSources
/gate/source/source1_6/attachTo cubeOfSources
/gate/source/source1_7/attachTo cubeOfSources
/gate/source/source0_8/attachTo cubeOfSources
/gate/source/source0_9/attachTo cubeOfSources
/gate/source/source0_10/attachTo cubeOfSources
/gate/source/source0_11/attachTo cubeOfSources
/gate/source/source0_12/attachTo cubeOfSources
/gate/source/source0_13/attachTo cubeOfSources
/gate/source/source0_14/attachTo cubeOfSources
/gate/source/source1_8/attachTo cubeOfSources
/gate/source/source1_9/attachTo cubeOfSources
/gate/source/source1_10/attachTo cubeOfSources
/gate/source/source1_11/attachTo cubeOfSources
/gate/source/source1_12/attachTo cubeOfSources
/gate/source/source1_13/attachTo cubeOfSources
/gate/source/source1_14/attachTo cubeOfSources


/gate/source/background/setActivity 90000 becquerel

#small sources (0.3 mm diameter), activity/mm3 = bg x 10
/gate/source/source0_0/setActivity 0.01269 becquerel
/gate/source/source0_1/setActivity 0.01269 becquerel
/gate/source/source0_2/setActivity 0.01269 becquerel
/gate/source/source0_3/setActivity 0.01269 becquerel
/gate/source/source0_4/setActivity 0.01269 becquerel
/gate/source/source0_5/setActivity 0.01269 becquerel
/gate/source/source0_6/setActivity 0.01269 becquerel
/gate/source/source0_7/setActivity 0.01269 becquerel
/gate/source/source1_0/setActivity 0.01269 becquerel
/gate/source/source1_1/setActivity 0.01269 becquerel
/gate/source/source1_2/setActivity 0.01269 becquerel
/gate/source/source1_3/setActivity 0.01269 becquerel
/gate/source/source1_4/setActivity 0.01269 becquerel
/gate/source/source1_5/setActivity 0.01269 becquerel
/gate/source/source1_6/setActivity 0.01269 becquerel
/gate/source/source1_7/setActivity 0.01269 becquerel
/gate/source/source1_0/setActivity 0.01269 becquerel

#big sources (1 mm diameter), activity/mm3 = bg x 10
/gate/source/source0_8/setActivity  3.7692 becquerel
/gate/source/source0_9/setActivity  3.7692 becquerel
/gate/source/source0_10/setActivity 3.7692 becquerel
/gate/source/source0_11/setActivity 3.7692 becquerel
/gate/source/source0_12/setActivity 3.7692 becquerel
/gate/source/source0_13/setActivity 3.7692 becquerel
/gate/source/source0_14/setActivity 3.7692 becquerel
/gate/source/source1_8/setActivity  3.7692 becquerel
/gate/source/source1_9/setActivity  3.7692 becquerel
/gate/source/source1_10/setActivity 3.7692 becquerel
/gate/source/source1_11/setActivity 3.7692 becquerel
/gate/source/source1_12/setActivity 3.7692 becquerel
/gate/source/source1_13/setActivity 3.7692 becquerel
/gate/source/source1_14/setActivity 3.7692 becquerel

#/gate/source/source0_0/visualize 1000 red 2
#/gate/source/source0_1/visualize 1000 red 2
#/gate/source/source0_2/visualize 1000 red 2
#/gate/source/source0_3/visualize 1000 red 2
#/gate/source/source0_4/visualize 1000 red 2
#/gate/source/source0_5/visualize 1000 red 2
#/gate/source/source0_6/visualize 1000 red 2
#/gate/source/source0_7/visualize 1000 red 2
#/gate/source/source1_0/visualize 1000 red 2
#/gate/source/source1_1/visualize 1000 red 2
#/gate/source/source1_2/visualize 1000 red 2
#/gate/source/source1_3/visualize 1000 red 2
#/gate/source/source1_4/visualize 1000 red 2
#/gate/source/source1_5/visualize 1000 red 2
#/gate/source/source1_6/visualize 1000 red 2
#/gate/source/source1_7/visualize 1000 red 2
#/gate/source/source0_8/visualize 1000 red 2
#/gate/source/source0_9/visualize 1000 red 2
#/gate/source/source0_10/visualize 1000 red 2
#/gate/source/source0_11/visualize 1000 red 2
#/gate/source/source0_12/visualize 1000 red 2
#/gate/source/source0_13/visualize 1000 red 2
#/gate/source/source0_14/visualize 1000 red 2
#/gate/source/source1_8/visualize 1000 red 2
#/gate/source/source1_9/visualize 1000 red 2
#/gate/source/source1_10/visualize 1000 red 2
#/gate/source/source1_11/visualize 1000 red 2
#/gate/source/source1_12/visualize 1000 red 2
#/gate/source/source1_13/visualize 1000 red 2
#/gate/source/source1_14/visualize 1000 red 2

